### PR TITLE
Fixes for regressions in local variable behavior.

### LINKED ISSUE #95: Comprehensions do not handle variables from parent scope correctly
Given the following policy:
scope.rego
```rego
package test

x = y {
	a = [1, 2, 3]
	y = {z | z = a[_]}
}
```

`rego-cpp/build/dist/bin/rego  -d scope.rego data.test.x` produces `[]`.
It is supposed to produce a set `{1, 2, 3}`. See https://play.openpolicyagent.org/p/AGT70depTf

### LINKED ISSUE #96: SEGV on framework.rego
Running the rego program on the framework.rego policy causes a segmentation fault.

```bash
$ dist/bin/rego -d ../tests/aci/framework.rego data
rego 0.3.10 (main:a24f12c, Tue, 2 Jan 2024 10:14:34 +0000)[AppleClang 15.0.0.15000100] on macos
Segmentation fault: 11
```

### LINKED ISSUE #97: Policy is not evaluated correctly when statements are not in order
```rego
package test

x = y {
 y = z
 z = 12
}
```

x is evaluated to {} instead of 12.

### PR DESCRIPTION
**Pull request by matajoh**
As a result of the optimization passes, some incorrect behavior was introduced for local variables. This commit restores correct functionality.

Fixes #95
Fixes #97 
Fixed #96

### CODE REVIEW

File: src/passes/init.cc [hunk 1]
```diff
@@ -135,22 +153,154 @@ namespace
...
+    std::vector<InitInfo> init_stmts;
+    std::transform(
+      init_stmt_for_local.begin(),
+      init_stmt_for_local.end(),
+      std::back_inserter(init_stmts),
+      [](auto& pair) { return pair.second; });
+
+    // sort the init statements so that statements with no local variables
+    // on one side come first.
+    std::sort(init_stmts.begin(), init_stmts.end(), [](auto& a, auto& b) {
```
Comment (mjp41) [inline src/passes/init.cc:215]: Is sorting sufficient here, or do you want a topological sort.

I guess I am worried about 
```
a = b
b = c
c = 1
```

Comment (matajoh) [reply src/passes/init.cc:215]: I tested that example and it does work, however, I think a topological sort is probably more principled. Good point.

Comment (matajoh) [reply src/passes/init.cc]: Updated code does a more principled sort as suggested, thanks again!
